module.exports = {
    BCRYPT_SALT_ROUNDS: 10,
    PASSWORD_RESET_KEY : 'mysecretkey',

    USER_ROLE_ID_ADMIN : 1,
    USER_ROLE_ID_STYLIST : 2,
    USER_ROLE_ID_SALON : 3,

    EXPERIENCE_ID_LESS_6_MONTHS : 1,
    EXPERIENCE_ID_6_MONTHS : 2,
    EXPERIENCE_ID_1_YEAR : 3,
    EXPERIENCE_ID_2_YEARS : 4,
    EXPERIENCE_ID_3_YEARS : 5,
    EXPERIENCE_ID_4_YEARS : 6,
    EXPERIENCE_ID_5_YEARS : 7,
    EXPERIENCE_ID_5_10_YEARS : 8,
    EXPERIENCE_ID_10_15_YEARS : 9,
    EXPERIENCE_ID_15_YEARS_PLUS : 10,
};