const AuthenticationTypes = {
    SIGIN_IN_SUCCESS: 'SIGIN_IN_SUCCESS',
    SIGIN_IN_FAILED: 'SIGIN_IN_FAILED',
    GET_AUTH_FROM_LOCAL_STORAGE_SUCCESS: 'GET_AUTH_FROM_LOCAL_STORAGE_SUCCESS',
    GET_AUTH_FROM_LOCAL_STORAGE_FAILED: 'GET_AUTH_FROM_LOCAL_STORAGE_FAILED',
    CLEAR_AUTH_FROM_LOCAL_STORAGE_SUCCESS: 'CLEAR_AUTH_FROM_LOCAL_STORAGE_SUCCESS',
    CLEAR_AUTH_FROM_LOCAL_STORAGE_FAILED: 'CLEAR_AUTH_FROM_LOCAL_STORAGE_FAILED',

}

const ExperienceTypes = {
    EXPERIENCES_FETCH_SUCCESS : 'EXPERIENCES_FETCH_SUCCESS',
    EXPERIENCES_FETCH_FAILED : 'EXPERIENCES_FETCH_FAILED'
}



module.exports = {
    AuthenticationTypes,
    ExperienceTypes
}